# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_library', '0003_book_bookgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookgenre',
            field=models.ManyToManyField(blank=True, to='E_library.genre_allot'),
        ),
    ]
