# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_library', '0005_auto_20171029_0646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genre_allot',
            unique_together=set([]),
        ),
    ]
