# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_library', '0007_auto_20171029_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Genre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
