# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_library', '0008_auto_20171112_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Group_id',
        ),
        migrations.AddField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
