# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 17:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_library', '0009_auto_20171112_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Fname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='Lname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='Mname',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
