# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 17:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_library', '0010_auto_20171115_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Fname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='Lname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='Mname',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='Phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Enter valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='Isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9-]*$', 'Enter valid ISBN number.')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='Isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_library.Book', validators=[django.core.validators.RegexValidator('^[0-9-]*$', 'Enter valid ISBN number.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='E_title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='event_genre',
            name='Genre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='genre_allot',
            name='Isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_library.Book', validators=[django.core.validators.RegexValidator('^[0-9-]*$', 'Enter valid ISBN number.')]),
        ),
        migrations.AlterField(
            model_name='genre_allot',
            name='genre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='Genre',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='Fname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='Lname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='Mname',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='Phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Enter valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='written_by',
            name='Isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_library.Book', validators=[django.core.validators.RegexValidator('^[0-9-]*$', 'Enter valid ISBN number.')]),
        ),
    ]
