# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 04:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_library', '0018_auto_20171116_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrows',
            name='ratings',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-10]$', 'Enter ratings 0-10.')]),
        ),
    ]
